spring:
  quartz:
    job-store-type: memory
    properties:
      org.quartz.threadPool.threadCount: 11
      org.quartz.threadPool.threadPriority: 5
      org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread: true